version: "3"

services:
  web:
    container_name: molior-web
    build:
      context: .
      dockerfile: docker/prod/web.Dockerfile

  molior:
    container_name: molior-server
    build:
      context: .
      dockerfile: docker/prod/molior.Dockerfile

  postgres:
    container_name: molior-postgres
    build:
      context: .
      dockerfile: docker/common/postgres.Dockerfile

  aptly:
    container_name: molior-aptly
    build:
      context: .
      dockerfile: docker/prod/aptly.Dockerfile

  nginx:
    container_name: molior-nginx
    build:
      context: .
      dockerfile: docker/common/nginx.Dockerfile

  registry:
    container_name: molior-registry
    build:
      context: .
      dockerfile: docker/common/registry.Dockerfile
